modLoader = "javafml"
loaderVersion = "[39,)"
issueTrackerURL = "https://github.com/MoonflowerTeam/${repo}/issues"
license = "GPLv3"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Chalkboard Mods"
credits = "Llamaman133, MiteBeMana"
description = "A mod inspired by Terraria's pots, adding pots that drop common loot that can make the early-game more rewarding."
displayURL = "https://www.moonflower.gg"
#updateJSONURL = ""
#logoFile = ""

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "pollen"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "BEFORE"
side = "BOTH"